version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '80:80'
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "tests"]